###########################################################
# +-----------------------------------------------------+ #
# |                      Settings                       | #
# +-----------------------------------------------------+ #
###########################################################

portals:
   # Can be a name or a ID
   portal-block: GOLD_BLOCK

signs:
   first-line: "[teleport]"